"""
BERT Textual Feature Extraction - Usage Examples
================================================

This file contains practical examples for using the BERT embeddings
generated by the 02_bert_textual_features.ipynb notebook.
"""

import numpy as np
import pandas as pd
from sklearn.metrics.pairwise import cosine_similarity
from sklearn.cluster import KMeans
from sklearn.linear_model import LogisticRegression
import pickle

# ============================================================================
# EXAMPLE 1: Load Embeddings
# ============================================================================

def load_embeddings():
    """Load BERT embeddings and metadata."""
    # Load all embeddings
    embeddings = np.load('models/bert_embeddings/bert_embeddings_all.npy')
    metadata = pd.read_csv('models/bert_embeddings/bert_metadata.csv')
    
    print(f"Loaded {len(embeddings):,} embeddings")
    print(f"Embedding shape: {embeddings.shape}")
    
    return embeddings, metadata


def load_platform_specific():
    """Load embeddings for specific platforms."""
    youtube_videos = np.load('models/bert_embeddings/bert_embeddings_youtube_videos.npy')
    twitter = np.load('models/bert_embeddings/bert_embeddings_twitter.npy')
    reddit = np.load('models/bert_embeddings/bert_embeddings_reddit.npy')
    
    return youtube_videos, twitter, reddit


# ============================================================================
# EXAMPLE 2: Semantic Similarity Search
# ============================================================================

def find_similar_texts(query_idx, embeddings, metadata, top_k=10):
    """
    Find texts most similar to a query text.
    
    Args:
        query_idx: Index of query text
        embeddings: BERT embeddings array
        metadata: Metadata DataFrame
        top_k: Number of similar texts to return
    
    Returns:
        DataFrame with similar texts and similarity scores
    """
    # Get query embedding
    query_embedding = embeddings[query_idx].reshape(1, -1)
    
    # Compute similarities
    similarities = cosine_similarity(query_embedding, embeddings)[0]
    
    # Get top-k indices (excluding query itself)
    top_indices = np.argsort(similarities)[-(top_k+1):-1][::-1]
    
    # Create result DataFrame
    results = metadata.iloc[top_indices].copy()
    results['similarity'] = similarities[top_indices]
    
    return results


def semantic_search(query_text, model, tokenizer, embeddings, metadata, top_k=10):
    """
    Search for texts semantically similar to a query string.
    
    Args:
        query_text: Text string to search for
        model: BERT model
        tokenizer: BERT tokenizer
        embeddings: Corpus embeddings
        metadata: Metadata DataFrame
        top_k: Number of results
    
    Returns:
        DataFrame with matching texts
    """
    import torch
    
    # Encode query
    inputs = tokenizer(query_text, return_tensors='pt', 
                      padding=True, truncation=True, max_length=512)
    
    with torch.no_grad():
        outputs = model(**inputs)
        query_embedding = outputs.last_hidden_state[:, 0, :].numpy()
    
    # Find similar
    similarities = cosine_similarity(query_embedding, embeddings)[0]
    top_indices = np.argsort(similarities)[-top_k:][::-1]
    
    results = metadata.iloc[top_indices].copy()
    results['similarity'] = similarities[top_indices]
    
    return results


# ============================================================================
# EXAMPLE 3: Content Clustering
# ============================================================================

def cluster_content(embeddings, n_clusters=10):
    """
    Cluster content based on semantic similarity.
    
    Args:
        embeddings: BERT embeddings
        n_clusters: Number of clusters
    
    Returns:
        Cluster labels and model
    """
    kmeans = KMeans(n_clusters=n_clusters, random_state=42, n_init=20)
    labels = kmeans.fit_predict(embeddings)
    
    return labels, kmeans


def analyze_clusters(embeddings, metadata, labels):
    """
    Analyze characteristics of each cluster.
    
    Args:
        embeddings: BERT embeddings
        metadata: Metadata DataFrame
        labels: Cluster labels
    
    Returns:
        Dictionary with cluster statistics
    """
    cluster_stats = {}
    
    for cluster_id in range(labels.max() + 1):
        mask = labels == cluster_id
        cluster_data = metadata[mask]
        
        cluster_stats[cluster_id] = {
            'size': mask.sum(),
            'platforms': cluster_data['platform'].value_counts().to_dict(),
            'sample_texts': cluster_data['cleaned_text'].sample(
                n=min(5, len(cluster_data))
            ).tolist()
        }
    
    return cluster_stats


# ============================================================================
# EXAMPLE 4: Brand-Influencer Matching
# ============================================================================

def compute_brand_alignment(brand_description, influencer_embeddings, 
                           model, tokenizer):
    """
    Compute semantic alignment between brand and influencer content.
    
    Args:
        brand_description: Brand description text
        influencer_embeddings: Embeddings of influencer content
        model: BERT model
        tokenizer: BERT tokenizer
    
    Returns:
        Array of similarity scores
    """
    import torch
    
    # Encode brand description
    inputs = tokenizer(brand_description, return_tensors='pt',
                      padding=True, truncation=True, max_length=512)
    
    with torch.no_grad():
        outputs = model(**inputs)
        brand_embedding = outputs.last_hidden_state[:, 0, :].numpy()
    
    # Compute similarities
    similarities = cosine_similarity(brand_embedding, influencer_embeddings)[0]
    
    return similarities


def find_matching_influencers(brand_description, embeddings, metadata,
                             model, tokenizer, top_k=20):
    """
    Find influencers whose content aligns with a brand.
    
    Args:
        brand_description: Brand description
        embeddings: All content embeddings
        metadata: Metadata with influencer info
        model: BERT model
        tokenizer: BERT tokenizer
        top_k: Number of top influencers
    
    Returns:
        DataFrame with top matching content
    """
    similarities = compute_brand_alignment(
        brand_description, embeddings, model, tokenizer
    )
    
    # Get top matches
    top_indices = np.argsort(similarities)[-top_k:][::-1]
    
    results = metadata.iloc[top_indices].copy()
    results['brand_alignment'] = similarities[top_indices]
    
    return results


# ============================================================================
# EXAMPLE 5: Sponsorship Detection
# ============================================================================

def train_sponsorship_detector(embeddings, labels):
    """
    Train a classifier to detect sponsored content.
    
    Args:
        embeddings: BERT embeddings
        labels: Binary labels (1=sponsored, 0=organic)
    
    Returns:
        Trained model
    """
    from sklearn.model_selection import train_test_split
    from sklearn.metrics import classification_report
    
    # Split data
    X_train, X_test, y_train, y_test = train_test_split(
        embeddings, labels, test_size=0.2, random_state=42
    )
    
    # Train classifier
    model = LogisticRegression(max_iter=1000)
    model.fit(X_train, y_train)
    
    # Evaluate
    y_pred = model.predict(X_test)
    print(classification_report(y_test, y_pred))
    
    return model


def predict_sponsorship(text, model, bert_model, tokenizer):
    """
    Predict if a text is sponsored content.
    
    Args:
        text: Input text
        model: Trained classifier
        bert_model: BERT model
        tokenizer: BERT tokenizer
    
    Returns:
        Probability of being sponsored
    """
    import torch
    
    # Extract BERT embedding
    inputs = tokenizer(text, return_tensors='pt',
                      padding=True, truncation=True, max_length=512)
    
    with torch.no_grad():
        outputs = bert_model(**inputs)
        embedding = outputs.last_hidden_state[:, 0, :].numpy()
    
    # Predict
    prob = model.predict_proba(embedding)[0, 1]
    
    return prob


# ============================================================================
# EXAMPLE 6: Multi-modal Integration (BERT + CLIP)
# ============================================================================

def combine_bert_clip(bert_embeddings, clip_embeddings):
    """
    Combine BERT textual and CLIP visual features.
    
    Args:
        bert_embeddings: BERT embeddings (N x 768)
        clip_embeddings: CLIP embeddings (N x 512)
    
    Returns:
        Combined embeddings (N x 1280)
    """
    # Simple concatenation
    combined = np.hstack([bert_embeddings, clip_embeddings])
    
    # Optional: Normalize each modality
    from sklearn.preprocessing import StandardScaler
    
    scaler_bert = StandardScaler()
    scaler_clip = StandardScaler()
    
    bert_norm = scaler_bert.fit_transform(bert_embeddings)
    clip_norm = scaler_clip.fit_transform(clip_embeddings)
    
    combined_norm = np.hstack([bert_norm, clip_norm])
    
    return combined, combined_norm


def weighted_multimodal_similarity(bert_emb1, clip_emb1, bert_emb2, clip_emb2,
                                   text_weight=0.6, visual_weight=0.4):
    """
    Compute weighted similarity using both text and visual features.
    
    Args:
        bert_emb1, bert_emb2: Text embeddings
        clip_emb1, clip_emb2: Visual embeddings
        text_weight: Weight for text similarity
        visual_weight: Weight for visual similarity
    
    Returns:
        Combined similarity score
    """
    text_sim = cosine_similarity(
        bert_emb1.reshape(1, -1),
        bert_emb2.reshape(1, -1)
    )[0, 0]
    
    visual_sim = cosine_similarity(
        clip_emb1.reshape(1, -1),
        clip_emb2.reshape(1, -1)
    )[0, 0]
    
    combined_sim = text_weight * text_sim + visual_weight * visual_sim
    
    return combined_sim


# ============================================================================
# EXAMPLE 7: Temporal Analysis
# ============================================================================

def analyze_temporal_trends(embeddings, metadata, time_column='published_at'):
    """
    Analyze how content themes evolve over time.
    
    Args:
        embeddings: BERT embeddings
        metadata: Metadata with timestamps
        time_column: Name of timestamp column
    
    Returns:
        Dictionary with temporal statistics
    """
    # Convert to datetime
    metadata['timestamp'] = pd.to_datetime(metadata[time_column])
    metadata['year_month'] = metadata['timestamp'].dt.to_period('M')
    
    # Cluster by time period
    temporal_analysis = {}
    
    for period in metadata['year_month'].unique():
        mask = metadata['year_month'] == period
        period_embeddings = embeddings[mask]
        
        # Compute centroid
        centroid = period_embeddings.mean(axis=0)
        
        temporal_analysis[str(period)] = {
            'count': mask.sum(),
            'centroid': centroid,
            'variance': period_embeddings.var(axis=0).mean()
        }
    
    return temporal_analysis


# ============================================================================
# EXAMPLE 8: Save and Load Models
# ============================================================================

def save_analysis_results(embeddings, metadata, clusters, filename):
    """Save analysis results for later use."""
    results = {
        'embeddings': embeddings,
        'metadata': metadata,
        'clusters': clusters
    }
    
    with open(filename, 'wb') as f:
        pickle.dump(results, f)
    
    print(f"Saved results to {filename}")


def load_analysis_results(filename):
    """Load previously saved analysis results."""
    with open(filename, 'rb') as f:
        results = pickle.load(f)
    
    return results['embeddings'], results['metadata'], results['clusters']


# ============================================================================
# EXAMPLE USAGE
# ============================================================================

if __name__ == "__main__":
    # Example workflow
    print("Loading embeddings...")
    embeddings, metadata = load_embeddings()
    
    print("\nFinding similar texts...")
    similar = find_similar_texts(query_idx=0, embeddings=embeddings, 
                                 metadata=metadata, top_k=5)
    print(similar[['cleaned_text', 'similarity']])
    
    print("\nClustering content...")
    labels, kmeans = cluster_content(embeddings, n_clusters=5)
    cluster_info = analyze_clusters(embeddings, metadata, labels)
    
    print("\nCluster sizes:")
    for cid, info in cluster_info.items():
        print(f"  Cluster {cid}: {info['size']} samples")
    
    print("\n✓ Examples complete!")
